package shell

import (
	_ "embed" // yes
	"io"
	"text/template"

	"github.com/cashapp/hermit/errors"
)

var (
	//go:embed files/sh_common_hooks.tmpl.sh
	commonHooksScript string
	commonHooksTmpl   = template.Must(template.New("commonHooks").Parse(commonHooksScript))
)

const (
	hookStartMarker = "# Generated by Hermit; START; DO NOT EDIT."
	hookEndMarker   = "# Generated by Hermit; END; DO NOT EDIT."
)

func commonHooks(w io.Writer, hermitBin string) error {
	err := commonHooksTmpl.Execute(w, struct{ HermitBin string }{HermitBin: hermitBin})
	return errors.WithStack(err)
}
