run:
  tests: true
  max-same-issues: 50

output:
  print-issued-lines: false

linters:
  enable-all: true
  disable:
    - megacheck
    - lll
    - typecheck # `go build` catches this, and it doesn't currently work with Go 1.11 modules
    - goimports # horrendously slow with go modules :(
    - dupl # has never been actually useful
    - gochecknoglobals
    - gochecknoinits
    - funlen
    - whitespace
    - godox
    - wsl
    - dogsled
    - gomnd
    - gocognit
    - gocyclo
    - godot
    - nestif
    - testpackage
    - goerr113
    - gci
    - gofumpt
    - nlreturn
    - cyclop
    - paralleltest
    - prealloc
    - nolintlint
    - varnamelen
    - nonamedreturns
    - nilnil
    - ireturn
    - exhaustruct
    - forcetypeassert
    - usestdlibvars
    - wrapcheck
    - tagliatelle
    - makezero
    - maintidx
    - nilerr
    - errchkjson
    - mnd      # overly sensitive to any number
    - tagalign # don't care about struct tag alignment (help:".." tends to be long)

linters-settings:
  govet:
    use-installed-packages: true
  dupl:
    threshold: 100
  goconst:
    min-len: 8
    min-occurrences: 3
  gocyclo:
    min-complexity: 20
  gocritic:
    disabled-checks:
      - ifElseChain
  exhaustive:
    default-signifies-exhaustive: true
  depguard:
    rules:
      main:
        deny:
          - pkg: errors
            desc: "use github.com/cashapp/hermit/errors"
          - pkg: github.com/pkg/errors
            desc: "use github.com/cashapp/hermit/errors"
  forbidigo:
    forbid:
      - '^fmt.Errorf'
      - '^os.User.*Dir'


issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-files:
    - cmd/protopkg/main.go
  exclude-dirs:
    - resources
    - old
  exclude:
    # Captured by errcheck.
    - '^(G104|G204):'
    # Very commonly not checked.
    - 'Error return value of .(.*\.Help|.*\.MarkFlagRequired|(os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*Print(f|ln|)|os\.(Un)?Setenv). is not checked'
    # Weird error only seen on Kochiku...
    - 'internal error: no range for'
    - 'exported method `.*\.(MarshalJSON|UnmarshalJSON|URN|Payload|GoString|Close|Provides|Requires|ExcludeFromHash|MarshalText|UnmarshalText|Description|Check|Poll|Severity)` should have comment or be unexported'
    - 'declaration of "err" shadows declaration'
    - 'by other packages, and that stutters'
    - 'Potential file inclusion via variable'
    - 'at least one file in a package should have a package comment'
    - 'bad syntax for struct tag pair'
    - 'should have.*comment'
    - 'uses unkeyed fields'
    - 'G307'
  exclude-rules:
    # Don't warn on unused parameters.
    # Parameter names are useful documentation--even when unused.
    # Replacing them with '_' is undesirable.
    - linters: [revive]
      text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'
