// Code generated by "stringer -linecomment -type CleanMask"; DO NOT EDIT.

package hermit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CleanBin-1]
	_ = x[CleanPackages-2]
	_ = x[CleanCache-4]
	_ = x[CleanAll - -1]
}

const (
	_CleanMask_name_0 = "all"
	_CleanMask_name_1 = "binpackages"
	_CleanMask_name_2 = "cache"
)

var (
	_CleanMask_index_1 = [...]uint8{0, 3, 11}
)

func (i CleanMask) String() string {
	switch {
	case i == -1:
		return _CleanMask_name_0
	case 1 <= i && i <= 2:
		i -= 1
		return _CleanMask_name_1[_CleanMask_index_1[i]:_CleanMask_index_1[i+1]]
	case i == 4:
		return _CleanMask_name_2
	default:
		return "CleanMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
