// Code generated by "stringer -linecomment -type PackageState"; DO NOT EDIT.

package manifest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PackageStateRemote-0]
	_ = x[PackageStateDownloaded-1]
	_ = x[PackageStateInstalled-2]
}

const _PackageState_name = "remotedownloadedinstalled"

var _PackageState_index = [...]uint8{0, 6, 16, 25}

func (i PackageState) String() string {
	if i < 0 || i >= PackageState(len(_PackageState_index)-1) {
		return "PackageState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PackageState_name[_PackageState_index[i]:_PackageState_index[i+1]]
}

func (s PackageState) MarshalJSON() ([]byte, error) {
	return []byte(`"` + s.String() + `"`), nil
}
