#!/bin/bash

set -eo pipefail

export HERMIT_USER_HOME=~

if [ -z "${HERMIT_STATE_DIR}" ]; then
  case "$(uname -s)" in
  Darwin)
    export HERMIT_STATE_DIR="${HERMIT_USER_HOME}/Library/Caches/hermit"
    ;;
  Linux)
    export HERMIT_STATE_DIR="${XDG_CACHE_HOME:-${HERMIT_USER_HOME}/.cache}/hermit"
    ;;
  esac
fi

export HERMIT_DIST_URL="${HERMIT_DIST_URL:-HERMIT_DEFAULT_DIST_URL}"
HERMIT_CHANNEL="$(basename "${HERMIT_DIST_URL}")"
export HERMIT_CHANNEL
export HERMIT_EXE=${HERMIT_EXE:-${HERMIT_STATE_DIR}/pkg/hermit@${HERMIT_CHANNEL}/hermit}

if [ ! -x "${HERMIT_EXE}" ]; then
  echo "Bootstrapping ${HERMIT_EXE} from ${HERMIT_DIST_URL}" 1>&2
  INSTALL_SCRIPT="$(mktemp)"
  # This value must match that of the install script
  INSTALL_SCRIPT_SHA256="HERMIT_INSTALL_SCRIPT_SHA256"
  # Install script is versioned by the first 10 characters of its sha256sum
  INSTALL_SCRIPT_VERSION=$(echo "${INSTALL_SCRIPT_SHA256}" | head -c 10)
  curl -fsSL "${HERMIT_DIST_URL}/install-${INSTALL_SCRIPT_VERSION}.sh" -o "${INSTALL_SCRIPT}"
  # Verify install script's sha256sum
  sha256sum "${INSTALL_SCRIPT}" | \
    awk -v EXPECTED="$INSTALL_SCRIPT_SHA256" \
    '$1!=EXPECTED {print "Install script sha256sum " $1 " does not match " EXPECTED; exit 1}'
  /bin/bash "${INSTALL_SCRIPT}" 1>&2
fi

exec "${HERMIT_EXE}" --level=fatal exec "$0" -- "$@"
