// Code generated by "stringer -linecomment -type Level"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelTrace-0]
	_ = x[LevelDebug-1]
	_ = x[LevelInfo-2]
	_ = x[LevelWarn-3]
	_ = x[LevelError-4]
	_ = x[LevelFatal-5]
}

const _Level_name = "tracedebuginfowarnerrorfatal"

var _Level_index = [...]uint8{0, 5, 10, 14, 18, 23, 28}

func (i Level) String() string {
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
