on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
name: Canary
jobs:
  canary:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Init Hermit
        uses: cashapp/activate-hermit@cea9af7913204a965fd488637a8d1811bba2e616 # v1
      - name: Build Hermit
        run: |
          just build canary linux amd64
          just build canary linux arm64
          just build canary darwin amd64
          just build canary darwin arm64
          INSTALLER_VERSION=$(go run -ldflags "-X main.channel=canary" ./cmd/hermit gen-installer --dest=build/install.sh)
          cp build/install.sh build/install-"${INSTALLER_VERSION}".sh
      - name: Release canary
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          tag: canary
          name: Canary
          allowUpdates: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
