on:
  push:
    branches:
      - master
name: Docs
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Init Hermit
        run: |
          ./bin/hermit env -r >> $GITHUB_ENV
          . ./bin/activate-hermit
          python -mvenv .venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Generate Schema Docs
        run: |
          make -C docs schema
      - name: Setup mkdocs
        working-directory: ./docs
        run: pip install -r requirements.txt
      - name: Publish Site
        working-directory: ./docs
        run: mkdocs gh-deploy --force
