on:
  push:
#    paths:
#      - 'docs/**'
    branches:
      - master
name: Docs
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x8
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Generate Schema Docs
        run: |
          make -C docs schema
      - name: Setup mkdocs
        working-directory: ./docs
        run: pip install -r requirements.txt
      - name: Publish Site
        working-directory: ./docs
        run: mkdocs gh-deploy --force
