on:
  push:
    paths-ignore:
      - "docs/**"
    tags:
      - "v*"
name: Release
jobs:
  deployable:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Init Hermit
        uses: cashapp/activate-hermit@e49f5cb4dd64ff0b0b659d1d8df499595451155a # ratchet:cashapp/activate-hermit@v1
      - name: Build Hermit
        run: |
          just build stable linux amd64
          just build stable linux arm64
          just build stable darwin amd64
          just build stable darwin arm64
          INSTALLER_VERSION=$(go run -ldflags "-X main.channel=stable" ./cmd/hermit gen-installer --dest=build/install.sh)
          cp build/install.sh build/install-"${INSTALLER_VERSION}".sh
      - name: Release versioned
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1
        with:
          allowUpdates: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release stable
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1
        with:
          tag: stable
          name: Stable
          allowUpdates: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
